import 'package:equatable/equatable.dart';

class CompletionStreamedChunkChoice extends Equatable {
  const CompletionStreamedChunkChoice({
    required this.text,
    required this.index,
    required this.finishReason,
  });

  const CompletionStreamedChunkChoice.empty()
      : text = '',
        index = 0,
        finishReason = '';

  /// The text generated by the completion.
  final String text;

  /// The index of the choice.
  final int index;

  /// The reason the completion finished.
  final String finishReason;

  @override
  List<Object?> get props => [
        text,
        index,
        finishReason,
      ];

  //copyWith
  CompletionStreamedChunkChoice copyWith({
    String? text,
    int? index,
    String? finishReason,
  }) {
    return CompletionStreamedChunkChoice(
      text: text ?? this.text,
      index: index ?? this.index,
      finishReason: finishReason ?? this.finishReason,
    );
  }
}
