import 'package:chatgpt_prompts/features/prompts/domain/model/completion_streamed_chunk_choice.dart';
import 'package:equatable/equatable.dart';

class CompletionStreamedChunk extends Equatable {
  const CompletionStreamedChunk({
    required this.id,
    required this.created,
    required this.choice,
    required this.model,
  });

  const CompletionStreamedChunk.empty()
      : id = '',
        created = '1970-01-01T00:00:00.000000Z',
        choice = const CompletionStreamedChunkChoice.empty(),
        model = '';

  /// The ID of the completion.
  final String id;

  /// The date the completion was created.
  final String created;

  /// The first choice generated by the completion.
  final CompletionStreamedChunkChoice choice;

  /// The model used to generate the completion.
  final String model;

  @override
  List<Object?> get props => [
        id,
        created,
        choice,
        model,
      ];

  CompletionStreamedChunk operator +(CompletionStreamedChunk other) {
    return CompletionStreamedChunk(
      id: other.id,
      created: other.created,
      choice: other.choice.copyWith(text: choice.text + other.choice.text),
      model: other.model,
    );
  }

  //copyWith
  CompletionStreamedChunk copyWith({
    String? id,
    String? created,
    CompletionStreamedChunkChoice? choice,
    String? model,
  }) {
    return CompletionStreamedChunk(
      id: id ?? this.id,
      created: created ?? this.created,
      choice: choice ?? this.choice,
      model: model ?? this.model,
    );
  }
}
